trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run lint
  displayName: 'Lint'

- script: |
    npm run vscode:prepublish
  displayName: 'Build'

- script: |
    npm install -g vsce
    mkdir build
    vsce package -o build/code-server-npm.vsix
  displayName: 'Package'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'vscode-extension'
    targetPath: 'build'